appName: RoutingService
logLevel: WARN

DEBUG: True
TESTING: True

database:
  mongo:
    dsn: mongodb://localhost:27017/routes
    name: routes

solver:
  APIs:
    openrouteservice:
      key: 5b3ce3597851110001cf6248b1912bd267da4496b237740d97e32861
