appName: RoutingService
logLevel: WARN

DEBUG: True
TESTING: False

HOST: 0.0.0.0
PORT: 5000

database:
  mongo:
    dsn: mongodb://mongo:27017/routes
    name: routes

solver:
  APIs:
    openrouteservice:
      key: 5b3ce3597851110001cf6248b1912bd267da4496b237740d97e32861
